name: Cypress Tests

on: 
  pull_request:
    branches:
      - main
      - devs

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Cypress run
        uses: cypress-io/github-action@v5.0.0 # use the explicit version number
        with:
          build: npm run build
          start: npm start